### ISSUE TITLE
at_mono | Implement better tooling across repositories

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_tools#157]
Lead: @XavierChanth 
I'd like to improve the overall dev experience in the organization.
I see a number of improvements that could be made, and I want to spend some time investigating them:

- [x] Automating painful chores, such as setting up some tools to update our archetype across all repositories `gitxargs`
- [x] Better tooling to catch cross package dependency issues. [at_mono](https://github.com/atsign-foundation/at_mono)
- [ ] Better repository-level tooling.
  -  [ ] pana for verifying before publishing
  -  [x] melos for maintaining multi package repositories
  - [ ] publishing tools from within `at_mono`
- [ ] Visualization tools to gain a better understanding of our repositories and packages.
- [x] Add semantic commit to repos

There are more things to be discovered and ideated.

**Comment by cpswan** [comment]
As mentioned on our call last week, I think [Atomist](https://atomist.com/) may be worth a look, though their present messaging of 'keep your containers safe' seems a little off track for us.

**Comment by xavierchanth** [comment]
From my research, it's unclear as to whether Atomist will save us time & effort or if it will just we another tool to manage. They claim to "solve the common parts" but don't support dart projects out of the box. I will investigate further.

**Comment by xavierchanth** [comment]
In PR39, I am going to start by putting together some workflows based on what I've done with at_app, and a few other opensource Flutter/Dart based workflows that I've found interesting.

**Comment by xavierchanth** [comment]
@cpswan shall we close this for the time being? I believe that we've accomplished the important stuff here, the rest can be revisited if we find the need.

**Comment by cpswan** [comment]
@XavierChanth agreed - closing
