### ISSUE TITLE
Regexp Builder

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_tools#192]
**Is your feature request related to a problem? Please describe.**

For developers new to the @‎platform it may be difficult to build regexp queries for keys since they may be:

- unfamiliar with the format of the keys
- inexperienced with regexp

**Describe the solution you'd like**

A utility class that makes it easy to build regexp expressions to query `AtKey`s

**Describe alternatives you've considered**

Better documentation around this, but I believe this to be more ideal.

**Additional context**
N/A

**Comment by xavierchanth** [comment]
Changing this to a high, to work on in PR39, this is important content for atsign.dev 3.

**Comment by ksanty** [comment]
@XavierChanth should we move up to high priority for work on PR43?

**Comment by xavierchanth** [comment]
Sure, I can begin this in PR43.

**Comment by xavierchanth** [comment]
Closing this due to low priority
