### ISSUE TITLE
Testability and Documentation for KeyStream

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_tools#193]
lead: @XavierChanth 

See also [at_client_sdk#519](https://github.com/atsign-foundation/at_client_sdk/issues/519)

See [this PR](https://github.com/atsign-foundation/at_client_sdk/pull/548).

Todos:
- [x] Write unit tests around at_stream package
- [x] Determine final repo for the package - my suggestion is at_client_sdk since end2end tests are required for this package
- [x] Complete usage + Documentation
- [x] Add onError callback parameter to all models

**Comment by xavierchanth** [comment]
@gkc Where should this live, within the SDK? separate package? I would like to put it in at_client_sdk so that I can take advantage of the end2end test suite. I think this could be used commonly enough that it could potentially be part of the SDK, instead of a separate package.

**Comment by gkc** [comment]
Yeah that's my feeling also, Xavier

**Comment by xavierchanth** [comment]
PR39: This ticket is complete, awaiting Gary's review.
