### ISSUE TITLE
Create a StdErrLoggingHandler and make it an option for AtSignLogger to use it instead of current ConsoleLoggingHandler

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_tools#268]
### Is your feature request related to a problem? Please describe.

Currently, in command-line programs like at_talk, register_cli, onboarding_cli etc, we can't choose to direct all AtSignLogger output to stderr, which prevents us from doing some normal Unix-y things with program outputs

### Describe the solution you'd like

Create a StdErrLoggingHandler and make it an option for AtSignLogger to use it instead of current ConsoleLoggingHandler. It needs to be optional, with the default continuing to be to use ConsoleLoggingHandler.

**Comment by gkc** [comment]
No progress in PR53 due to other priorities

**Comment by sitaram-kalluri** [comment]
The changes are completed and pushed to the following branch: [StdErr_Impl](https://github.com/atsign-foundation/at_tools/tree/stderr_impl)

The branch is open for testing to hear suggestions before raising a PR to merge the changes.

Spent 3SP in PR-54

**Comment by sitaram-kalluri** [comment]
The changes are published in at_utils v3.0.13
