### ISSUE TITLE
Create Demos for LoraWan gateway administration and management

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_tools#320]
### Gateway management at scale

Gateway management gets challenging when there are multiple gateways involved, over time different gateways need different configuration files, firewalls, static IPs, and managing that and getting the right config file to the right gateway is fraught with the possibility of human error.

Colin will demonstrate a much easier open source gateway management with the following highlights:

- [x] Multiple config files going to the correct gateway automatically

- [x] No ports open on the LAN or WAN interfaces (just localhost), so invisible on the network

- [x] All communication end-to-end encrypted

- [x] No need for fixed IP addresses

- [x] No need for firewall configurations (NAT) or VPN's to manage the gateway

**Comment by cconstab** [comment]
@gkc calling this done or just started? !

**Comment by gkc** [comment]
Done for demo purposes I think. You agree?

**Comment by xavierchanth** [comment]
Moving this to "For Review"
