### ISSUE TITLE
Command line way to get CRAM key

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_tools#321]

**Comment by cconstab** [comment]
Any progress on this ?

**Comment by gkc** [comment]
Nobody assigned to it and its state is still Triage so I guess not. @srieteja have you done any work on this?

**Comment by gkc** [comment]
@cconstab I think the priority this sprint was getting cram key from the registrar UI; from command line in the coming sprint

**Comment by cconstab** [comment]
Ok in that case I will release sshnp v3.1.0 with at_activate_cli as is and when we have this task complete produce a new release. The knock on effect is documentation and video guides. So can we discuss more in sprint planning ?

Thanks

**Comment by gkc** [comment]
If it'll save a bunch of future rework I can take care of this tomorrow; let me know

**Comment by cconstab** [comment]
No need to work on a Sunday! But lets make a priority for first half of sprint. That way the rest of the team can work on videos and step by step insructions.

I have to get regional sshrvd atSigns up as well.

**Comment by srieteja** [comment]
> Nobody assigned to it and its state is still Triage so I guess not. @srieteja have you done any work on this?

I have worked on this, the following is the PR for fetching cram using registrar https://github.com/atsign-foundation/at_libraries/pull/343

I believe this ticket is a duplicate of https://github.com/atsign-foundation/at_libraries/issues/330

**Comment by cconstab** [comment]
Dupe
