### ISSUE TITLE
at_cli - fix open issues and improve documentation

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_tools#48]
- [ ] Actually wider than just below the at_cli needs to work as well as being documented
- [ ] Wider scope to include [at_cli](https://docs.google.com/document/d/1IFshAcWYLyBlNuQMjaryirWp2SEmtIDUYNdRc9b-kG0/edit#heading=h.rvxv7ixjkdf6)

Who is it for?

- [ ] System admins wanting to send data from scripts
- [ ] Use for near real-time updates of telemetry

How do they use it?

- [ ] On Linux machines (often IoT) within scripts

What commands/verbs can be passed (or at least where's the docs explaining that)?

- [x] MVP verbs to be able to use would be (Update/Delete/Scan/Lookup)
- [x] Null safety changes
- [x] Help text
- [x] Update README document with samples to use the tool
How can/should the config be modified?

**Comment by cpswan** [comment]
The [PKAM README](https://github.com/atsign-foundation/at_tools/blob/trunk/at_pkam/README.md) implemented in #66 can be used as a template for this.

**Comment by cconstab** [comment]
@kalluriramkumar could you take a look at this .. I can get simple at_cli commands to run but not more complex ones..

```
cconstab@Liberator:~/at_tools/at_cli$ dart bin/main.dart -?
Invalid command. Verb or command not entered
null
cconstab@Liberator:~/at_tools/at_cli$ dart bin/main.dart -c lookup:location.wavi@colin
data:{"location":"bootjack california","radius":"2 mi"}
cconstab@Liberator:~/at_tools/at_cli$ dart bin/main.dart -a -c update:hello@colin hello
Invalid command. Verb or command not entered
null
cconstab@Liberator:~/at_tools/at_cli$ dart bin/main.dart -c scan -r twitter
data:["about.wavi@colin","at_followers_of_self.wavi@colin","at_following_by_self.wavi@colin","custom_callsign.wavi@colin","custom_catch-upandbookameeting.wavi@colin","custom_inthenews.wavi@colin","custom_jeeping.wavi@colin","custom_myfirstprofessionalcomputer.wavi@colin","custom_proverb.wavi@colin","custom_quoteoftheday.wavi@colin","discord.wavi@colin","email.wavi@colin","facebook.wavi@colin","firstname.wavi@colin","image.wavi@colin","instagram.wavi@colin","lastname.wavi@colin","linkedin.wavi@colin","location.wavi@colin","locationnickname.wavi@colin","phone.wavi@colin","profilepic.buzz@colin","pronoun.wavi@colin","publickey@colin","signing_publickey@colin","steam.wavi@colin","twitter.wavi@colin","xbox.wavi@colin","youtube.wavi@colin"]
cconstab@Liberator:~/at_tools/at_cli$
```

Needs more documentation and some samples of 

lookup 
update
notify
etc

**Comment by naresh0689** [comment]
MVP features and README changes are done. At_client integration will be taken care as part of https://github.com/atsign-foundation/at_client_sdk/issues/223
