### ISSUE TITLE
at_cram README.md needs to explain what the tool does

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_tools#49]
@cconstab initial commit is a good starting point `Very simple command line tool to create cram digest from cramkey and challenge in the @protocol.`

What is a cram digest and why do I want one?

How do I use the tool?

What is the purpose of a lib that calculates 42 and a test that looks for 42?

- [x] Artifact of the devtool (intelij) and dart

**Comment by cpswan** [comment]
The [PKAM README](https://github.com/atsign-foundation/at_tools/blob/trunk/at_pkam/README.md) implemented in #66 can be used as a template for this.

**Comment by cconstab** [comment]
Added some better instructions and removed un needed lib..
