### ISSUE TITLE
at_ve_doctor README.md needs to explain what the tool does

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_tools#51]
@cconstab initial commit is a good starting point `Small demo/tool to check that your virtual environment is up and working working and that all the @Signs are ready and activated..`

Where do I get the virtual environment (VE) from, and how is this going to help me with it?

How do I use the tool?

What is the purpose of a lib that calculates 42 and a test that looks for 42?

**Comment by cpswan** [comment]
The [PKAM README](https://github.com/atsign-foundation/at_tools/blob/trunk/at_pkam/README.md) implemented in #66 can be used as a template for this.

**Comment by cconstab** [comment]
Added documentation and examples.. Updated FQDN for VE2.0
